"""
Export helpers: recipe text, CSV, and optional Excel (openpyxl formatted).
Pure; no UI code.
"""

from __future__ import annotations
from pathlib import Path
from typing import Dict, List
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, Border, Side, PatternFill
from openpyxl.utils.dataframe import dataframe_to_rows


def make_recipe_text(rec: Dict) -> str:
    lines = [
        "Backyard Seed Advisor — Custom Mix Recipe",
        f"Region: {rec['region']} | Season: {rec['season']}",
        f"Birds considered: {', '.join(rec['selected_birds']) or 'None (generic)'}",
        "",
        "Recommended proportional mix (by weight):",
    ]
    for label, pct in rec["recipe"]:
        lines.append(f"  {pct:5.0f}%  {label}")
    lines.append("")
    lines.append("Top single seeds to offer (in separate feeders if possible):")
    for s in rec["top_seeds"]:
        lines.append(f"  • {s}")
    if rec["notes"]:
        lines.append("")
        lines.append("Notes:")
        for n in rec["notes"]:
            lines.append(f"  - {n}")
    lines.append("")
    lines.append("Generated by https://github.com/altustd/bird-seed-recommender")
    return "\n".join(lines)


def make_scores_df(rec: Dict) -> pd.DataFrame:
    rows = []
    for seed, info in rec["per_seed"].items():
        rows.append(
            {
                "Seed": info["label"],
                "Match %": info["score"],
                "Regional/Seasonal Mult": info["mult"],
                "Why for your birds": info["why"],
                "Tip": info["tip"],
            }
        )
    return pd.DataFrame(rows).sort_values("Match %", ascending=False)


def save_recipe_txt(rec: Dict, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(make_recipe_text(rec), encoding="utf-8")
    return path


def save_scores_csv(rec: Dict, path: Path) -> Path:
    df = make_scores_df(rec)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)
    return path


def save_excel(rec: Dict, path: Path) -> Path:
    """Formatted workbook with Recipe + Scores sheets."""
    wb = Workbook()

    # Sheet 1: Recipe
    ws1 = wb.active
    ws1.title = "Recipe"
    ws1["A1"] = "Backyard Seed Advisor — Recommended Mix"
    ws1["A1"].font = Font(bold=True, size=14)
    ws1["A3"] = f"Region: {rec['region']}"
    ws1["A4"] = f"Season: {rec['season']}"
    ws1["A5"] = "Birds: " + (", ".join(rec["selected_birds"]) or "generic")
    ws1["A7"] = "Seed"
    ws1["B7"] = "% of mix"
    ws1["C7"] = "Notes"
    for cell in ws1[7]:
        if cell.value:
            cell.font = Font(bold=True)
            cell.fill = PatternFill(start_color="E2E4EC", end_color="E2E4EC", fill_type="solid")

    row = 8
    for label, pct in rec["recipe"]:
        ws1[f"A{row}"] = label
        ws1[f"B{row}"] = pct
        ws1[f"C{row}"] = rec["per_seed"][[k for k, v in rec["per_seed"].items() if v["label"] == label][0]]["tip"][:60] + "..."
        row += 1

    ws1.column_dimensions["A"].width = 26
    ws1.column_dimensions["B"].width = 10
    ws1.column_dimensions["C"].width = 55

    # Sheet 2: Scores
    ws2 = wb.create_sheet("Scores")
    df = make_scores_df(rec)
    for r_idx, row in enumerate(dataframe_to_rows(df, index=False, header=True), 1):
        for c_idx, val in enumerate(row, 1):
            cell = ws2.cell(row=r_idx, column=c_idx, value=val)
            if r_idx == 1:
                cell.font = Font(bold=True)
                cell.fill = PatternFill(start_color="4F8EF7", end_color="4F8EF7", fill_type="solid")
                cell.font = Font(bold=True, color="FFFFFF")
            cell.alignment = Alignment(wrap_text=True, vertical="top")

    ws2.column_dimensions["A"].width = 24
    ws2.column_dimensions["B"].width = 10
    ws2.column_dimensions["C"].width = 12
    ws2.column_dimensions["D"].width = 32
    ws2.column_dimensions["E"].width = 50

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(path)
    return path